### ISSUE TITLE
images not showing up properly on carrds

### ISSUE THREAD

**Issue by cr4shlove** [kuiperdog/wav.haus#1]
it might be something with the "hide made with carrd" function, but when using a carrd link images don't show up properly
![IMG_1011](https://github.com/kuiperdog/wav.haus/assets/140276557/9933529f-0d7b-433e-a659-b994e8372bd1)
![IMG_1010](https://github.com/kuiperdog/wav.haus/assets/140276557/272d36a0-a16c-45cf-a177-2e1d50420298)

**Comment by kuiperdog** [comment]
Thanks for reporting this! Looking into it now.

**Comment by kuiperdog** [comment]
Found the issue. In the Carrd option, you're only supposed to write the subdomain (the part before the 'carrd.co'), but you wrote the full domain, meaning it looking for the images at "yourname.carrd.co.carrd.co". I've changed your record now, and I'll add a safeguard against this soon.
![image](https://github.com/kuiperdog/wav.haus/assets/130880623/2a38ecd6-6b00-4b58-89ce-9b9ec2fe13c6)
