### ISSUE TITLE
link won't open

### ISSUE THREAD

**Issue by idk-182992018** [kuiperdog/wav.haus#2]
Idk how to use github sorry if i wrote this two times 😭, hi so i created a domain a week ago and no matter how many times i add a link or anything it won't show up it's been like this for a week, it always pops up as a new page for example 원영.wav.haus you can see it won't redirect to the link..

**Comment by kuiperdog** [comment]
Hello! Due to inconsistent support across other platforms and certain browser limitations, wav.haus currently only supports subdomains with alphanumeric characters. I'd recommend re-creating your link with the romanized form of your desired subdomain, if it is available.
